# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: "/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "servizi" # Used in routes, e.g., /admin/collections/blog
    label: "Servizi" # Used in the UI
    folder: "_servizi" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - label: "Pagine"
    name: "pages"
    files:
      - label: "Azienda"
        name: "azienda"
        file: azienda.md
        fields:
          - {label: "Titolo", name: "title", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
          - {label: "Featured Image", name: "thumbnail", widget: "image"}

      - label: "Chi Siamo"
        name: "chisiamo"
        file: chisiamo.md
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured Image", name: "thumbnail", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefono", name: "telefono", widget: "string"}
          
          - {label: "Title", name: "title2", widget: "string"}
          - {label: "Featured Image", name: "thumbnail2", widget: "image"}
          - {label: "Body", name: "body2", widget: "markdown"}
          - {label: "Email", name: "email2", widget: "string"}
          - {label: "Telefono", name: "telefono2", widget: "string"}
      
  
